#!/usr/bin/env bash
# Copyright 2023-2026 AVSystem <avsystem@avsystem.com>
# AVSystem Anjay Lite LwM2M SDK
# All rights reserved.
#
# Licensed under AVSystem Anjay Lite LwM2M Client SDK - Non-Commercial License.
# See the attached LICENSE file for details.

# ensure venv is used
VENV_DIR="${VENV_DIR:-venv}"
if python3 -c 'import sys; exit(0) if sys.base_prefix != sys.prefix else exit(1)'; then
    echo "Using already activated Python venv"
else
    if [ ! -d "${VENV_DIR}" ]; then
        echo "Creating Python venv in ${VENV_DIR}"
        python3 -m venv "${VENV_DIR}"
    fi

    echo "Activating Python venv in ${VENV_DIR}"

    source "${VENV_DIR}/bin/activate"
    python3 -m pip install --upgrade pip
    python3 -m pip install -r requirements.txt
fi
