# Copyright 2023-2026 AVSystem <avsystem@avsystem.com>
# AVSystem Anjay Lite LwM2M SDK
# All rights reserved.
#
# Licensed under AVSystem Anjay Lite LwM2M Client SDK - Non-Commercial License.
# See the attached LICENSE file for details.

"""
This module implements "build once, reuse many" for tests that need a compiled
test application.

Key ideas:
- Each distinct AppConfig dict maps to a stable build directory name (hash).
- Build directories live in pytest's persistent cache (not auto-cleaned),
  allowing reuse across separate pytest invocations.
- In pytest-xdist runs, collection happens on every worker. We coordinate via a
  lock file in a run-unique temp dir so exactly one worker performs the builds.
"""

import pytest
import filelock
import tempfile
import uuid
import hashlib
import json
import subprocess

from pathlib import Path
from typing import Any

AppConfig = dict[str, Any]

APP_SRC_DIR = Path(__file__).parent / "app"
RUN_UID_KEY = pytest.StashKey[str]()


def hash_config(cfg: AppConfig) -> str:
    # Stable key for a config dict. We rely on sort_keys=True to keep the hash
    # identical for semantically equal dicts (order-independent).
    cfg_str = json.dumps(cfg, sort_keys=True)
    return hashlib.md5(cfg_str.encode(), usedforsecurity=False).hexdigest()


def get_run_uid(config: pytest.Config) -> str:
    # If xdist is used, each worker receives a testrunuid value generated by
    # the controller. We can use this to derive a temporary directory unique
    # just for this run.
    if hasattr(config, "workerinput"):
        return config.workerinput["testrunuid"]

    # If xdist is not used, we just generate a stub random UUID and cache it for
    # the duration of the test run.
    uid = config.stash.get(RUN_UID_KEY, None)
    if uid is None:
        uid = uuid.uuid4().hex
        config.stash[RUN_UID_KEY] = uid
    return uid


def ensure_session_tmpdir(session: pytest.Session) -> Path:
    tmpdir = Path(tempfile.gettempdir()) / \
        f"pytest-{get_run_uid(session.config)}"
    tmpdir.mkdir(exist_ok=True, parents=True)
    return tmpdir


def ensure_build_dir(session: pytest.Session) -> Path:
    # pytest's cache directory (typically .pytest_cache/d/) is persistent between
    # runs, which is exactly what we want for incremental CMake builds.
    # This is intentionally *not* a per-run tmp dir.
    return session.config.cache.mkdir("build")


def ensure_mbedtls_build_dir(session: pytest.Session) -> Path:
    # mbedtls is built as part of the app build, but it has a separate build dir
    # to allow sharing the same mbedtls build between multiple app configs.
    return ensure_build_dir(session) / "mbedtls"


def ensure_app_build_dir(session: pytest.Session, cfg: AppConfig) -> Path:
    build_dir = ensure_build_dir(session)
    cfg_hash = hash_config(cfg)
    app_build_dir = build_dir / cfg_hash
    app_build_dir.mkdir(exist_ok=True, parents=True)
    return app_build_dir


def is_skipped_at_collection_time(item: pytest.Item) -> bool:
    # NOTE: This utility is used to avoid prebuilding app configs for tests that
    # are eagerly skipped - not only this is a time saver, but also it allows
    # skipped tests to have invalid app configs without causing failures.
    if item.get_closest_marker("skip") is not None:
        return True

    for m in item.iter_markers("skipif"):
        cond = m.kwargs.get("condition", m.args[0] if m.args else False)
        if cond:
            return True

    return False


def try_getting_parametrized_app_cfg(item: pytest.Item) -> AppConfig | None:
    # After collection, each test item that is parametrized with an app config
    # will have a item.callspec.params["app"] attribute.
    callspec = getattr(item, "callspec", None)
    if callspec is None:
        return None

    params = getattr(callspec, "params", None)
    if params is None:
        return None

    return params.get("app", None)


def collect_all_app_cfgs(session: pytest.Session):
    # Runs after collection (called from conftest.py's pytest_collection_finish).
    # At this point session.items contains all tests, and for parametrized tests
    # pytest has attached call specs that we can introspect.
    distinct_cfgs = {}

    for item in session.items:
        if is_skipped_at_collection_time(item):
            continue
        if not "app" in item.fixturenames:
            continue
        cfg = try_getting_parametrized_app_cfg(item) or {}
        cfg_hash = hash_config(cfg)
        distinct_cfgs[cfg_hash] = cfg

    return distinct_cfgs.values()


def build_app(cfg: AppConfig, build_dir: Path):
    # This invokes CMake configure + build. The actual output executable name
    # ("test_app") is a CMake-side convention.
    #
    # This is cheap-ish to run each time upon startup if nothing changes in the
    # app, and at the same time it ensures that if something changes in the app
    # sources, the app will be rebuilt.

    options = [f"-D{key}={value}" for key, value in cfg.items()]

    subprocess.run([
        "cmake",
        "-S", APP_SRC_DIR,
        "-B", build_dir,
        *options
    ], check=True)

    subprocess.run([
        "cmake",
        "--build", build_dir,
        "--parallel"
    ], check=True)


def build_mbedtls(build_dir: Path):
    subprocess.run([
        "cmake",
        "-S", "mbedtls",
        "-B", build_dir
    ], check=True)

    subprocess.run([
        "cmake",
        "--build", build_dir,
        "--parallel"
    ], check=True)


def ensure_all_configs_prebuilt(session: pytest.Session):
    cfgs = collect_all_app_cfgs(session)

    session_tmpdir = ensure_session_tmpdir(session)
    lock_path = session_tmpdir / "prebuild.lock"
    success_path = session_tmpdir / "prebuild.success"
    error_path = session_tmpdir / "prebuild.error"

    # Per xdist docs, regardless of the number of workers, the test collection
    # process is done by each worker independently, and only after the
    # collection is finished, the controller dictates which of the collected
    # tests will be run by each worker.
    #
    # This allows us to assume that each worker sees the same set of test items
    # during collection, so we just pick the first worker that manages to
    # acquire the lock to be in charge of prebuilding the app configs, while
    # others will either see prebuild.success file and continue with the run,
    # or see prebuild.error and bail out immediately.
    #
    # https://pytest-xdist.readthedocs.io/en/stable/how-it-works.html
    with filelock.UnixFileLock(lock_path):
        try:
            if success_path.exists():
                return
            if error_path.exists():
                raise RuntimeError("Prebuild failed in another worker")

            mbedtls_build_dir = ensure_mbedtls_build_dir(session)
            build_mbedtls(mbedtls_build_dir)
            mbedtls_install_dir = mbedtls_build_dir / "_deps" / "mbedtls-install"

            for cfg in cfgs:
                build_dir = ensure_app_build_dir(session, cfg)
                build_dir.mkdir(exist_ok=True, parents=True)

                cfg_with_default_mbedtls = {
                    "MBEDTLS_ROOT_DIR": str(mbedtls_install_dir), **cfg}
                build_app(cfg_with_default_mbedtls, build_dir)

            success_path.touch()
        except Exception as e:
            error_path.touch()
            raise e
